name: Testing CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  hro-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Failing the Job
        run: php artisan serve

      - name: Running Tests
        run: echo "Tested"      
  
  hro-cd:
    needs: hro-ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Running Scripts 
        run: echo "Deployed"
