name: Testing CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  hro-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Lint PHP Files
        run: find . -type f -name '*.php' -print0 | xargs -0 -n1 -P4 php -l -n | (! grep -v "No syntax errors detected" )
  
  hro-cd:
    needs: hro-ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: SSH into the server
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{secret.REMOTE_HOST}}
          username: ${{secret.REMOTE_USERNAME}}
          key: ${{secret.SSH_PRIVATE_KEY}} 
          port: 22
          script: |
            cd /var/www/html/project/
            sudo git pull origin
            ... 
