on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: SSH into the server
        uses: appleboy/ssh-action@v1.0.3
        with: 
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          port: 22
          script: |
            sudo mkdir -p /var/www/html/project/
            sudo chown 777 /var/www/html/project/
            cd /var/www/html/project/
            sudo git pull origin
