on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    
    steps:
    - name: Debug Secret
      run: |
        if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
          echo "SSH_PRIVATE_KEY is empty!"
        else
          echo "SSH_PRIVATE_KEY is set (hidden in logs)."
        fi
          
    - name: upload a simple file
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        echo "Secret is: ${{ secrets.SERVER_IP }}"
        echo "::add-mask::${{ secrets.SERVER_IP }}"
        echo "After masking: ${{ secrets.SERVER_IP }}"  
        touch file
        scp -i $SSH_PRIVATE_KEY file $SERVER_USER@$SERVER_IP:.
